version: '2'
services:
  web:
    build: .
    ports:
     - "80:8080"
    volumes:
      - ./www:/var/www
    links:
     - appdb
    environment:
      LUCEE_PASSWORD: MakeThisSecretLuceeAdminPassword!
      MYSQL_ROOT_PASSWORD : MakeThisSecretMySQLRootPassword!
      MYSQL_HOST : appdb
      MYSQL_DATABASE : appdatabase
  appdb:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : MakeThisSecretMySQLRootPassword!
      MYSQL_DATABASE : appdatabase